### ISSUE TITLE
Be able to skip payment

### ISSUE THREAD

**Issue by jdeveloper** [Sylius/ShopApiPlugin#597]
Actualy, if I apply a coupon that makes the cart to be at cost 0, payment is removed, witch is correct. But the issue is, there is no way to complete the checkout neither is there an endpoint to skip payment.

**Comment by lchrusciel** [comment]
`payment_skipped` transition should be resolved dynamically, therefore there should be a possibility just to skip next state and finalize an order. 

Nevertheless, we should cover this case with the test.

**Comment by mamazu** [comment]
We need to add tests for this. The behaviour is working. Maybe the shipping cost is still not 0. If your order value is 0 and you have enabled skipping payments in your channel it will skip the payment.
